### ISSUE TITLE
Config for JSON layout

### ISSUE THREAD

**Issue by andrus** [bootique/bootique-logback#57]
Outputting logs as JSON (a common format for structured logging) simplifies downstream log processing, e.g. tokenization for log storage, [filtering by AWS CloudWatch](https://docs.aws.amazon.com/AmazonCloudWatch/latest/logs/FilterAndPatternSyntax.html), etc.

Logback supports [a JSON appender](https://www.baeldung.com/java-log-json-output), but we need to expose its configuration in Bootique, so that it can be setup as easily as "console" and "file" appenders

**Comment by stariy95** [comment]
I would like to grab this one

**Comment by andrus** [comment]
Be my guest :)

**Comment by stariy95** [comment]
FYI here is some thoughts about the implementation.

I've read logback docs and think that it's better to implement layout support in the Bootique rather than just add custom JSON appender. It would be more flexible and users could mix and match log format and logging destinations.
We could easily keep current `PatternLayout` as a default so it would be completely compatible with our current config format.

And moreover, we could add some Layouts that are already present in the logback core: `HTMLLayout` and `XMLLayout`.

It would look like this in the config:
```yaml
  appenders:
    - type: file
      name: test
      file: test.json
      layout:
        type: json
        timestampFormat: "yyyy-MM-dd HH:mm"
```

And I think that we should move JSON layout support to a separate module (`bootique-logback-json`) as it requires two additional dependencies, that are not useful for anything else.

**Comment by andrus** [comment]
> I've read logback docs and think that it's better to implement layout support in the Bootique rather than just add custom JSON appender. 

@stariy95 , yeah, you are right. Appender is more of a "medium" where the logs are written (console, file). Format is a layout. So the task title is misleading.

> And I think that we should move JSON layout support to a separate module (bootique-logback-json) as it requires two additional dependencies, that are not useful for anything else.

Agreed
